package com.example.familysafety.billing

/**
 * Every value here is a placeholder. This build is not shippable until all four are filled
 * in for real — the app will compile and run, but no purchase will verify and every grant
 * code will fail, which is deliberately loud rather than silently trusting an unset key.
 */
object BillingConfig {

    /** Play Console → Monetize → Products → Subscriptions. Must match exactly. */
    const val SUBSCRIPTION_PRODUCT_ID = "TODO_PLACEHOLDER_family_monthly"

    /**
     * Play Console → Monetize → Setup → Monetization setup → Licensing. This is the app's
     * public licensing key, base64, safe to ship — it can only verify a purchase, not forge
     * one. [com.android.billingclient] purchases carry an RSA-SHA1 signature over their JSON;
     * this is what verifies it.
     */
    const val PLAY_LICENSE_PUBLIC_KEY_BASE64 = "TODO_PLACEHOLDER_PLAY_LICENSE_KEY"

    /**
     * Public half of the grant-code signing keypair generated by
     * `tools/gen_grant_signing_key.py`. Also safe to ship. The matching private key never
     * leaves the developer's machine — see that script's header.
     */
    const val GRANT_PUBLIC_KEY_HEX = "TODO_PLACEHOLDER_GRANT_PUBLIC_KEY_HEX"

    /**
     * Epoch millis of the release that first enforces the paywall. Set exactly once, right
     * before that release ships, and never change it afterward — every family created before
     * this instant is grandfathered permanently, and moving it retroactively ungrandfathers
     * real families.
     */
    const val PAYWALL_INTRODUCED_AT_EPOCH_MS = Long.MAX_VALUE
}
