package com.example.familysafety.billing

/**
 * All four values are real as of the 2026-09-26 release that first enforces the paywall.
 */
object BillingConfig {

    /** Play Console → Monetize → Products → Subscriptions → "Family Safety Membership". */
    const val SUBSCRIPTION_PRODUCT_ID = "monthly.jibaro.familysafety.subscription"

    /**
     * Play Console → Monetize → Setup → Monetization setup → Licensing. The app's public
     * licensing key, base64, safe to ship — it can only verify a purchase, not forge one.
     * [com.android.billingclient] purchases carry an RSA-SHA1 signature over their JSON;
     * this is what verifies it. Confirmed to decode as a real 2048-bit RSA public key before
     * being pasted in here — a corrupted copy/paste would otherwise fail silently at runtime.
     */
    const val PLAY_LICENSE_PUBLIC_KEY_BASE64 =
        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuOIbVKpvQXAyn8LmQFVOYhIXFqTPj9dX6RZHP6BPSDhS0cYa5EFb4a9vEELsEgJ8+4CFtEaWBmw2kplnXgryb6QGxp+mVrk5c0C9nJHjXCY59m9l9YajH45EZvdaHfJFrdsc2yTWlKKehI5P509pVxYhmQPuajW5esaVlIBzJayMonO0T/Kfk2ZxpZd3tSyNuxnDZK+oXyZiArgVxUAe0H/zfqtBoiG7mtdOxiFB+trW3wg6uXd97ISeIWB5pLc6nENrSJ1Lk4i4cf2z2NQpNRGYZzkKbqVFoyEkttq9LoyObF+nKJxsAua8Hz3kktjqj3wY/dJkH0oLnKvoMI/BcwIDAQAB"

    /**
     * Public half of the grant-code signing keypair generated by
     * `tools/gen_grant_signing_key.py`. Also safe to ship. The matching private key never
     * leaves the developer's machine — see that script's header.
     */
    const val GRANT_PUBLIC_KEY_HEX = "dbbc75e3815d546de11fabbbdf03138c275bc2d407b3818905b06668d2fcff2f"

    /**
     * Epoch millis of the release that first enforces the paywall. Set exactly once, on
     * 2026-09-26, and must never change afterward — every family created before this instant
     * (every family that exists as of this release, including the developer's own) is
     * grandfathered permanently. A family created from this instant onward gets the 60-day
     * trial, then needs a subscription or grant code.
     */
    const val PAYWALL_INTRODUCED_AT_EPOCH_MS = 1790483432067L
}
