package com.example.familysafety.billing

/**
 * Two of these four are still placeholders. This build is not shippable until they're all
 * filled in for real — the app will compile and run, but no purchase will verify and every
 * grant code will fail, which is deliberately loud rather than silently trusting an unset key.
 */
object BillingConfig {

    /** Play Console → Monetize → Products → Subscriptions → "Family Safety Membership". */
    const val SUBSCRIPTION_PRODUCT_ID = "monthly.jibaro.familysafety.subscription"

    /**
     * Play Console → Monetize → Setup → Monetization setup → Licensing. The app's public
     * licensing key, base64, safe to ship — it can only verify a purchase, not forge one.
     * [com.android.billingclient] purchases carry an RSA-SHA1 signature over their JSON;
     * this is what verifies it. Confirmed to decode as a real 2048-bit RSA public key before
     * being pasted in here — a corrupted copy/paste would otherwise fail silently at runtime.
     */
    const val PLAY_LICENSE_PUBLIC_KEY_BASE64 =
        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuOIbVKpvQXAyn8LmQFVOYhIXFqTPj9dX6RZHP6BPSDhS0cYa5EFb4a9vEELsEgJ8+4CFtEaWBmw2kplnXgryb6QGxp+mVrk5c0C9nJHjXCY59m9l9YajH45EZvdaHfJFrdsc2yTWlKKehI5P509pVxYhmQPuajW5esaVlIBzJayMonO0T/Kfk2ZxpZd3tSyNuxnDZK+oXyZiArgVxUAe0H/zfqtBoiG7mtdOxiFB+trW3wg6uXd97ISeIWB5pLc6nENrSJ1Lk4i4cf2z2NQpNRGYZzkKbqVFoyEkttq9LoyObF+nKJxsAua8Hz3kktjqj3wY/dJkH0oLnKvoMI/BcwIDAQAB"

    /**
     * Public half of the grant-code signing keypair generated by
     * `tools/gen_grant_signing_key.py`. Also safe to ship. The matching private key never
     * leaves the developer's machine — see that script's header.
     */
    const val GRANT_PUBLIC_KEY_HEX = "TODO_PLACEHOLDER_GRANT_PUBLIC_KEY_HEX"

    /**
     * Epoch millis of the release that first enforces the paywall. Set exactly once, right
     * before that release ships, and never change it afterward — every family created before
     * this instant is grandfathered permanently, and moving it retroactively ungrandfathers
     * real families.
     */
    const val PAYWALL_INTRODUCED_AT_EPOCH_MS = Long.MAX_VALUE
}
